<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use App\Form\UploadAvatar;
use App\Form\Model\ChangeAvatar;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use App\Entity\User;
use App\Entity\Inventory;
use App\Entity\Item;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\DBAL\Driver\Connection;
use Symfony\Component\HttpFoundation\File\File;

class DefaultController extends AbstractController
{



    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        if(!$this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY')){
            return $this->redirectToRoute('hub');
        }

        return $this->redirectToRoute('app_login');
    }

    /**
     * @Route("/hub", name="hub")
     */
    public function hub()
    {
        $user = $this->getUser();

        $inventory = $this->getDoctrine()
            ->getRepository(Inventory::class)
            ->findBy(array('user' => $user->getId()));

        return $this->render('pages/hub.html.twig', [
            'title' => 'Hub',
            'avatar' => $user->getAvatar(),
            'username' => '@'.$user->getUsername(),
            'level' => $user->getLevel().' level',
            'items' => count($inventory),
        ]);
    }

    /**
     * @Route("/trading", name="trading")
     */
    public function trading()
    {
        return $this->render('pages/trading.html.twig');
    }

    /**
     * @Route("/achievements", name="achievements")
     */
    public function achievements()
    {
        return $this->render('pages/achievements.html.twig');
    }

    /**
     * @Route("/settings", name="settings")
     */
    public function settings(Request $request)
    {
        $user = $this->getUser();

        $avatar = new ChangeAvatar();
        $form = $this->createForm(UploadAvatar::class, $avatar);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $avatar->getAvatar();
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            try {
                $file->move(
                    $this->getParameter('avatars_directory'),
                    $fileName
                );
            } catch (FileException $e) {

            }
            $user->setAvatar($fileName);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->merge($user);
            $entityManager->flush();
            return $this->redirectToRoute('settings');
        }

        return $this->render('pages/settings.html.twig', [
            'email' => $user->getEmail(),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/items", name="items")
     */
    public function items()
    {
        $user = $this->getUser();
        $inventory = $this->getDoctrine()
            ->getRepository(Inventory::class)
            ->findBy(array('user' => $user->getId()));
        $items = $this->getDoctrine()
            ->getRepository(Item::class)
            ->findBy(array('id' => $inventory));

        return $this->render('pages/items.html.twig', [
            'count' => count($items),
            'items' => $items,
        ]);
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout()
    {
        return $this->redirectToRoute('index');
    }
}